name: class_info
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  pedantic: ^1.10.0
dependencies: 
  dcli: ^0.41.16
  excel: ^1.1.5
  mysql1: ^0.17.1
